"""
Mint Scan v8 — Report Generator
Supports: Markdown (.md), HTML (.html), PDF (reportlab or html→wkhtmltopdf).
"""
import os, time, json
from datetime import datetime
from logger import get_logger

log = get_logger('reports')


class ReportGenerator:
    def __init__(self, target_name: str, report_type: str = "Security Audit"):
        self.target    = target_name
        self.type      = report_type
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        ts_short       = datetime.now().strftime('%H%M%S')
        safe           = target_name.replace('.','_').replace(':','_').replace('/','_')
        self.filename_base = f"mint_scan_{safe}_{ts_short}"
        self.sections  = []
        log.info(f'ReportGenerator init: {report_type} / {target_name}')

    def add_section(self, title: str, content, level: str = "INFO"):
        self.sections.append({'title': title, 'content': content, 'level': level})

    # ── MARKDOWN ─────────────────────────────────────────────────
    def generate_markdown(self) -> str:
        lines = [
            "# MINT SCAN v8 — SECURITY REPORT",
            f"**Type:** {self.type}",
            f"**Target:** {self.target}",
            f"**Generated:** {self.timestamp}",
            f"**Tool:** Mint Scan v8.0 — Mint Projects PTY (Ltd), Pretoria",
            "",
            "---",
            "",
        ]
        for sec in self.sections:
            lines.append(f"## {sec['title']}")
            lvl_mark = {'CRITICAL':'🔴','HIGH':'🟠','WARN':'🟡',
                        'INFO':'🔵','OK':'🟢'}.get(sec['level'].upper(), '⚪')
            lines.append(f"**Severity:** {lvl_mark} {sec['level']}")
            lines.append("")
            c = sec['content']
            if isinstance(c, list):
                for item in c:
                    if isinstance(item, dict):
                        for k, v in item.items():
                            lines.append(f"- **{k}:** {v}")
                        lines.append("")
                    else:
                        lines.append(f"- {item}")
            else:
                lines.append(str(c))
            lines.append("")
        lines += ["---",
                  "*Generated by Mint Scan Linux v8 — Mint Projects PTY (Ltd)*",
                  "*github.com/mintpro004/mint-scan-linux-V8*"]
        return "\n".join(lines)

    # ── HTML ─────────────────────────────────────────────────────
    def generate_html(self) -> str:
        sev_colors = {'CRITICAL':'#ff5555','HIGH':'#ffaa33',
                      'WARN':'#ffcc44','INFO':'#55aaff','OK':'#44ff99'}
        rows = ""
        for sec in self.sections:
            col = sev_colors.get(sec['level'].upper(), '#7fb8d8')
            c   = sec['content']
            if isinstance(c, list):
                body = "<ul>" + "".join(
                    f"<li>{' — '.join(f'<b>{k}</b>: {v}' for k,v in item.items()) if isinstance(item, dict) else str(item)}</li>"
                    for item in c) + "</ul>"
            else:
                body = f"<p>{c}</p>"
            rows += f"""
            <div class="section">
              <div class="sec-hdr" style="border-left:4px solid {col}">
                <span class="sec-title">{sec['title']}</span>
                <span class="badge" style="background:{col};color:#05111f">{sec['level']}</span>
              </div>
              {body}
            </div>"""

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Mint Scan v8 — {self.type}</title>
<style>
  body{{background:#05111f;color:#e8f4ff;font-family:'Courier New',monospace;
        max-width:960px;margin:0 auto;padding:32px}}
  h1{{color:#00ffe0;border-bottom:2px solid #1a3f5c;padding-bottom:12px}}
  .meta{{color:#7fb8d8;font-size:12px;margin:8px 0 24px}}
  .section{{background:#0a1f35;border:1px solid #1a3f5c;border-radius:6px;
            margin:12px 0;padding:16px}}
  .sec-hdr{{display:flex;justify-content:space-between;align-items:center;
            padding-left:10px;margin-bottom:10px}}
  .sec-title{{font-size:14px;font-weight:bold;color:#e8f4ff}}
  .badge{{padding:3px 10px;border-radius:3px;font-size:10px;font-weight:bold}}
  ul{{margin:0;padding-left:20px;color:#9ecce8;font-size:13px;line-height:1.8}}
  p{{color:#9ecce8;font-size:13px;line-height:1.7}}
  b{{color:#e8f4ff}}
  .footer{{margin-top:32px;font-size:10px;color:#3a5a70;text-align:center}}
</style>
</head>
<body>
<h1>[ MINT SCAN ] v8 — {self.type}</h1>
<div class="meta">
  Target: <b>{self.target}</b> &nbsp;|&nbsp;
  Generated: <b>{self.timestamp}</b> &nbsp;|&nbsp;
  Tool: Mint Scan v8.0 — Mint Projects PTY (Ltd)
</div>
{rows}
<div class="footer">
  Generated by Mint Scan Linux v8 &nbsp;·&nbsp;
  github.com/mintpro004/mint-scan-linux-V8 &nbsp;·&nbsp;
  Mint Projects PTY (Ltd), Pretoria
</div>
</body>
</html>"""

    # ── PDF ──────────────────────────────────────────────────────
    def generate_pdf(self, out_path: str) -> tuple[bool, str]:
        """
        Export to PDF.
        Method 1: reportlab (pip install reportlab)
        Method 2: wkhtmltopdf CLI
        Method 3: Save HTML and instruct user
        """
        # Try reportlab
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib import colors
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.platypus import (SimpleDocTemplate, Paragraph,
                                             Spacer, HRFlowable, Table, TableStyle)
            from reportlab.lib.units import mm

            doc    = SimpleDocTemplate(out_path, pagesize=A4,
                                       leftMargin=20*mm, rightMargin=20*mm,
                                       topMargin=20*mm, bottomMargin=20*mm)
            styles = getSampleStyleSheet()

            # Custom styles
            title_style = ParagraphStyle('MintTitle', parent=styles['Heading1'],
                                         textColor=colors.HexColor('#00ffe0'),
                                         fontSize=18, spaceAfter=6)
            meta_style  = ParagraphStyle('MintMeta',  parent=styles['Normal'],
                                         textColor=colors.HexColor('#7fb8d8'),
                                         fontSize=8, spaceAfter=12)
            sec_style   = ParagraphStyle('MintSec',   parent=styles['Heading2'],
                                         textColor=colors.HexColor('#e8f4ff'),
                                         fontSize=12, spaceBefore=12, spaceAfter=4)
            body_style  = ParagraphStyle('MintBody',  parent=styles['Normal'],
                                         textColor=colors.HexColor('#9ecce8'),
                                         fontSize=9, leading=14)

            sev_rgb = {
                'CRITICAL': colors.HexColor('#ff5555'),
                'HIGH':     colors.HexColor('#ffaa33'),
                'WARN':     colors.HexColor('#ffcc44'),
                'INFO':     colors.HexColor('#55aaff'),
                'OK':       colors.HexColor('#44ff99'),
            }

            elems = [
                Paragraph("[ MINT SCAN ] v8 — Security Report", title_style),
                Paragraph(
                    f"Type: <b>{self.type}</b> &nbsp;|&nbsp; "
                    f"Target: <b>{self.target}</b> &nbsp;|&nbsp; "
                    f"Generated: {self.timestamp}", meta_style),
                HRFlowable(width="100%", thickness=1,
                            color=colors.HexColor('#1a3f5c')),
                Spacer(1, 8),
            ]

            for sec in self.sections:
                lvl_col = sev_rgb.get(sec['level'].upper(),
                                      colors.HexColor('#7fb8d8'))
                elems.append(Paragraph(sec['title'], sec_style))
                c = sec['content']
                if isinstance(c, list):
                    for item in c:
                        if isinstance(item, dict):
                            for k, v in item.items():
                                elems.append(Paragraph(
                                    f"<b>{k}:</b> {v}", body_style))
                        else:
                            elems.append(Paragraph(f"• {item}", body_style))
                else:
                    elems.append(Paragraph(str(c), body_style))
                elems.append(Spacer(1, 6))

            elems += [
                HRFlowable(width="100%", thickness=1,
                            color=colors.HexColor('#1a3f5c')),
                Paragraph(
                    "Generated by Mint Scan Linux v8 — "
                    "github.com/mintpro004/mint-scan-linux-V8 — "
                    "Mint Projects PTY (Ltd), Pretoria",
                    ParagraphStyle('Footer', parent=styles['Normal'],
                                   textColor=colors.HexColor('#3a5a70'),
                                   fontSize=7)),
            ]

            doc.build(elems)
            log.info(f'PDF (reportlab): {out_path}')
            return True, out_path

        except ImportError:
            pass

        # Try wkhtmltopdf
        import shutil, subprocess
        if shutil.which('wkhtmltopdf'):
            html_tmp = out_path.replace('.pdf', '_tmp.html')
            with open(html_tmp, 'w') as f:
                f.write(self.generate_html())
            r = subprocess.run(
                f'wkhtmltopdf --quiet "{html_tmp}" "{out_path}"',
                shell=True, capture_output=True, timeout=30)
            try:
                os.remove(html_tmp)
            except Exception:
                pass
            if r.returncode == 0 and os.path.exists(out_path):
                log.info(f'PDF (wkhtmltopdf): {out_path}')
                return True, out_path

        # Fallback: save HTML with instructions
        html_path = out_path.replace('.pdf', '.html')
        with open(html_path, 'w') as f:
            f.write(self.generate_html())
        msg = (f'PDF tools not found. Report saved as HTML: {html_path}\n'
               f'Install: pip install reportlab  OR  sudo apt install wkhtmltopdf')
        log.warning(msg)
        return False, msg

    # ── SAVE ─────────────────────────────────────────────────────
    def save_report(self, folder: str = "~/Documents/MintScan_Reports",
                    fmt: str = "md") -> str:
        folder = os.path.expanduser(folder)
        os.makedirs(folder, exist_ok=True)
        ext    = {'md': '.md', 'html': '.html', 'pdf': '.pdf'}.get(fmt, '.md')
        path   = os.path.join(folder, self.filename_base + ext)

        if fmt == 'pdf':
            ok, result = self.generate_pdf(path)
            return result
        elif fmt == 'html':
            with open(path, 'w') as f:
                f.write(self.generate_html())
        else:
            with open(path, 'w') as f:
                f.write(self.generate_markdown())

        log.info(f'Report saved ({fmt}): {path}')
        return path


def prompt_save_report(parent, target: str, report_type: str,
                        sections: list, default_fmt: str = 'html'):
    """
    GUI dialog: export report as Markdown, HTML, or PDF.
    sections = [(title, content, level), ...]
    """
    import customtkinter as ctk
    from widgets import C, Btn

    gen = ReportGenerator(target, report_type)
    for title, content, level in sections:
        gen.add_section(title, content, level)

    popup = ctk.CTkToplevel(parent)
    popup.title("Export Security Report")
    popup.geometry("520x340")
    popup.configure(fg_color=C['bg'])
    popup.attributes('-topmost', True)

    ctk.CTkLabel(popup, text="📋  EXPORT REPORT",
                 font=('Courier', 14, 'bold'),
                 text_color=C['ac']).pack(pady=(20, 4))
    ctk.CTkLabel(popup,
                 text=f"Target: {target}   |   Type: {report_type}",
                 font=('Courier', 9), text_color=C['tx']).pack(pady=2)

    fmt_var = ctk.StringVar(value=default_fmt)
    fmts = ctk.CTkFrame(popup, fg_color='transparent')
    fmts.pack(pady=10)
    for val, lbl in [('md', '📝 Markdown'), ('html', '🌐 HTML'), ('pdf', '📄 PDF')]:
        ctk.CTkRadioButton(fmts, text=lbl, variable=fmt_var, value=val,
                           font=('Courier', 10), text_color=C['tx'],
                           fg_color=C['ac'], border_color=C['br']
                           ).pack(side='left', padx=10)

    msg_lbl = ctk.CTkLabel(popup, text="Choose format then save or view.",
                            font=('Courier', 9), text_color=C['mu'])
    msg_lbl.pack(pady=6)

    btn_row = ctk.CTkFrame(popup, fg_color='transparent')
    btn_row.pack(pady=14)

    def do_save():
        fmt  = fmt_var.get()
        path = gen.save_report(fmt=fmt)
        msg_lbl.configure(text=f"✓ Saved: {path}", text_color=C['ok'])

    def do_view():
        fmt  = fmt_var.get()
        path = gen.save_report(fmt=fmt)
        os.system(f"xdg-open '{path}' 2>/dev/null || evince '{path}' 2>/dev/null || gedit '{path}' 2>/dev/null &")
        popup.destroy()

    Btn(btn_row, "💾 SAVE",     command=do_save, variant='primary', width=120).pack(side='left', padx=8)
    Btn(btn_row, "👁 VIEW NOW", command=do_view, variant='blue',    width=120).pack(side='left', padx=8)
    Btn(btn_row, "✗ CLOSE",    command=popup.destroy, variant='ghost', width=90).pack(side='left', padx=8)
