"""
Mint Scan v7 — Report Generator
Generates detailed security audits, investigation logs, and network reports.
Supports Text, Markdown, and HTML.
"""
import os
import time
import json
from datetime import datetime

class ReportGenerator:
    def __init__(self, target_name, report_type="General Audit"):
        self.target = target_name
        self.type = report_type
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.filename_base = f"mint_scan_{target_name.replace('.','_').replace(':','_')}_{datetime.now().strftime('%H%M%S')}"
        self.sections = []

    def add_section(self, title, content, level="INFO"):
        """Add a section to the report. Content can be a string or a list of dicts."""
        self.sections.append({
            'title': title,
            'content': content,
            'level': level
        })

    def generate_markdown(self):
        md = f"# MINT SCAN SECURITY REPORT\n"
        md += f"**Type:** {self.type}\n"
        md += f"**Target:** {self.target}\n"
        md += f"**Generated:** {self.timestamp}\n\n"
        md += "---\n\n"

        for sec in self.sections:
            md += f"## {sec['title']}\n"
            if isinstance(sec['content'], list):
                for item in sec['content']:
                    if isinstance(item, dict):
                        for k, v in item.items():
                            md += f"- **{k}:** {v}\n"
                        md += "\n"
                    else:
                        md += f"- {item}\n"
            else:
                md += f"{sec['content']}\n"
            md += "\n"

        md += "---\n*Generated by Mint Scan Linux v7 — Security Auditing Suite*"
        return md

    def save_report(self, folder="~/Documents/MintScan_Reports"):
        folder = os.path.expanduser(folder)
        if not os.path.exists(folder):
            os.makedirs(folder, exist_ok=True)
        
        path = os.path.join(folder, f"{self.filename_base}.md")
        with open(path, 'w') as f:
            f.write(self.generate_markdown())
        return path

def prompt_save_report(parent, target, report_type, sections):
    """GUI Helper to prompt user to save a report."""
    import customtkinter as ctk
    from widgets import C, Btn
    
    gen = ReportGenerator(target, report_type)
    for title, content, level in sections:
        gen.add_section(title, content, level)
        
    popup = ctk.CTkToplevel(parent)
    popup.title("Export Security Report")
    popup.geometry("500x300")
    popup.configure(fg_color=C['bg'])
    popup.attributes('-topmost', True)
    
    ctk.CTkLabel(popup, text="📋  REPORT GENERATED", font=('Courier',14,'bold'), text_color=C['ac']).pack(pady=(20,10))
    ctk.CTkLabel(popup, text=f"Target: {target}\nType: {report_type}", font=('Courier',10), text_color=C['tx']).pack(pady=5)
    
    msg_lbl = ctk.CTkLabel(popup, text="Would you like to save this investigation report?", font=('Courier',9), text_color=C['mu'])
    msg_lbl.pack(pady=10)
    
    btn_row = ctk.CTkFrame(popup, fg_color='transparent')
    btn_row.pack(pady=20)
    
    def do_save():
        path = gen.save_report()
        msg_lbl.configure(text=f"✓ Saved to: {path}", text_color=C['ok'])
        save_btn.configure(state='disabled')
        
    def do_open():
        path = gen.save_report()
        os.system(f"xdg-open '{path}' &")
        popup.destroy()

    save_btn = Btn(btn_row, "💾 SAVE REPORT", command=do_save, variant='primary', width=160)
    save_btn.pack(side='left', padx=10)
    
    Btn(btn_row, "👁 VIEW NOW", command=do_open, variant='blue', width=160).pack(side='left', padx=10)
    Btn(popup, "CLOSE", command=popup.destroy, variant='ghost').pack(pady=10)
